version: '3.9'
name: 'dnd-ezpz'

services:
        mysql:
                image: mysql
                container_name: mysql-test
                ports:
                        - ${DATABASE_PORT}:3306
                command: --default-authentication-plugin=caching_sha2_password --sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
                restart: always
                volumes:
                        - dbdata:/var/lib/mysql
                env_file:
                        - .env.test
                environment:
                        - MYSQL_USER=${DATABASE_USERNAME}
                        - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
                        - MYSQL_PASSWORD=${DATABASE_PASSWORD}
                        - MYSQL_DATABASE=${DATABASE_NAME}
                healthcheck:
                        test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
                        timeout: 20s
                        retries: 10
volumes:
        dbdata:
                name: mysql-test-volume
