# .github/actions/cached-deps/action.yml
name: 'Get & Cache Dependencies'
description: 'Get & Cache Dependencies(via npm) for faster builds'
runs:
        using: 'composite'
        steps:
                - name: Compute dependency
                  id: compute_lockfile_hash_key
                  run: echo "hash=${{ hashFiles('**/package-lock.json') }}" >> $GITHUB_OUTPUT
                  shell: bash

                - name: Cache node_modules
                  id: cache-node-modules
                  uses: actions/cache@v2
                  with:
                          path: node_modules
                          key: ${{ steps.compute_lockfile_hash_key.outputs.hash }}

                - name: Is Cache Hit
                  run: |
                          if [ ${{ steps.cache-node-modules.outputs.cache-hit }} == 'true' ]; then
                            echo "✅ cache hit!"
                          else
                            echo "🚫 cache hit failed!"
                          fi
                  shell: bash

                - name: Install dependencies
                  if: steps.cache-node-modules.outputs.cache-hit != 'true'
                  run: npm install
                  shell: bash
